Merge from palacios git tree (and other changes). - Support guest OS running under palacios virtualization layer. - Reworked patch to move as much as possible to x86_64 architecture   specific files and directories.  Only architecture-independent   files to have palacios-specific code added are init/main.c and   the top-level Makefile. init/main.c will eventually have the   palacios code removed once there is an API for starting guests.   I couldn't figure out a way to move the palacios stuff in the   top-level Makefile to arch/x86_64/kernel/Makefile. - Add CONFIG_PALACIOS and CONFIG_PALACIOS_PATH to x86_64 Kconfig for   enabling palacios hypervisor. - Add arch/x86_64/boot/Kconfig for configuring the 'make isoimage'   target. Arguments passed to the kernel, the init task ELF image,   the guest OS isoimage, etc. are now configured with 'make config'. - Default to an IO-APIC in the normal place if there is no mptable. - Added keyboard interrupt handler, forwards key presses to   palacios if it is enabled. - Implemented vprintk(). - Link in ROM BIOS and VGA BIOS images for use by the palacios layer.
These changes were the result of a 2.5 day meeting between
Northwestern, Sandia, and the University of New Mexico with the goal
of getting the Northwestern/UNM V3VEE project's Palacios hypervisor
layer working under Kitten.

Contributors:
Patrick Bridges (UNM)
Zheng CUI (UNM)
Peter Dinda (Northwestern)
Trammell Hudson (Sandia)
Jack Lange (Northwestern)
Kevin Pedretti (Sandia)
Patrick Widener (UNM)

diff --git a/arch/x86_64/boot/Makefile b/arch/x86_64/boot/Makefile
--- a/arch/x86_64/boot/Makefile
+++ b/arch/x86_64/boot/Makefile
@@ -54,11 +54,23 @@ $(obj)/setup $(obj)/bootsect: %: %.o FORCE
 $(obj)/compressed/vmlwk: FORCE
 	$(Q)$(MAKE) $(build)=$(obj)/compressed IMAGE_OFFSET=$(IMAGE_OFFSET) $@
 
+# Arguments to pass to the kernel
+# The '$(shell echo ...)' is needed to get rid of the surrounding quotes
+# that Kconfig insists on adding to string types. Same trick used below.
+KERNEL_ARGS = $(shell echo $(CONFIG_KERNEL_ARGS))
+
+ifdef CONFIG_PALACIOS
+# The initrd is the ISO image to use for the guest OS booted by Palacios
+FDINITRD = $(shell echo $(CONFIG_PALACIOS_GUESTOS_IMAGE))
+# This prevents a make "no rule" error (isoimage target depends on FDINITRD)
+$(FDINITRD):
+else
+# The initrd is the ELF image to use for the initial user-level task
+FDINITRD = $(shell echo $(CONFIG_INIT_TASK_IMAGE))
+endif
+
 # Set this if you want to pass append arguments to the isoimage kernel
-#FDARGS = serial.baud=115200 serial.kgdb=1 console=vga kgdbwait=1 kgdboc_console=serial debug_mptable=1 init_argv="one two three" init_envp="one=1 two=2 three=3" 
-FDARGS = console=vga,serial debug_mptable=1 init_argv="one two three" init_envp="one=1 two=2 three=3" 
-# Set this if you want an initrd included with the isoimage kernel
-FDINITRD = init_task
+FDARGS = $(KERNEL_ARGS) init_argv=$(CONFIG_INIT_TASK_ARGS) init_envp=$(CONFIG_INIT_TASK_ENVS)
 
 image_cmdline = default lwk $(FDARGS) $(if $(FDINITRD),initrd=initrd.img,)
 
@@ -75,8 +87,14 @@ isoimage: $(BOOTIMAGE) $(FDINITRD)
 	done
 	cp $(BOOTIMAGE) $(obj)/isoimage/lwk
 	echo '$(image_cmdline)' > $(obj)/isoimage/isolinux.cfg
-	if [ -f '$(FDINITRD)' ] ; then \
-		cp '$(FDINITRD)' $(obj)/isoimage/initrd.img ; \
+	@if [ -f '$(FDINITRD)' ] ; then \
+		echo 'initrd: $(FDINITRD)'; \
+		cp $(FDINITRD) $(obj)/isoimage/initrd.img ; \
+	elif [ -z '$(FDINITRD)' ]; then \
+		echo "initrd: None"; \
+	else \
+		echo >&2 'initrd: $(FDINITRD) not found!'; \
+		exit 1; \
 	fi
 	mkisofs -J -r -o $(obj)/image.iso -b isolinux.bin -c boot.cat \
 		-no-emul-boot -boot-load-size 4 -boot-info-table \
